Added postProcess, stem, and xmlDir fixes to xml.py for AM5 xml issues
jkrasting/dora pull request #21
Opened 2023-01-26 16:13 UTC by GFDL-Eric

2023-01-31 20:59 UTC, jkrasting requested changes

2023-01-31 20:59 UTC, jkrasting commented on dora/xml.py
> +
Hi @GFDL-Eric - can you apply the black code formatter to this file?

```
pip install black #(if you haven't already)
black xml.py
```

2023-01-31 22:10 UTC, GFDL-Eric commented on dora/xml.py
> +
@jkrasting done

2023-02-01 00:25 UTC, jkrasting approved these changes

2023-02-01 00:25 UTC, merged